version: '3.8'
services:
  app:
    container_name: portfolio-website2
    build:
      context: .
      target: build
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start 